// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"flashcards/database"
	"flashcards/logger"
	"flashcards/resources"
	"flashcards/server"
	"flashcards/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	engine := resources.NewGinEngine()
	loggerLogger, err := logger.NewLogger()
	if err != nil {
		return nil, err
	}
	serverServer := server.NewServer(engine, loggerLogger)
	return serverServer, nil
}

func InitializeDatabase() (*gorm.DB, error) {
	db, err := database.NewDatabase()
	if err != nil {
		return nil, err
	}
	return db, nil
}

func InitializeUserService(db *gorm.DB, logger2 *logger.Logger) services.UserService {
	userService := services.NewUserService(logger2, db)
	return userService
}
